#!/bin/bash

(make clean; make) || exit 1

source ../../tester/testall

runtest test_array "test1" none 1 3
runtest test_array "test2" none 1 3
runtest test_array "test3" none 1 3
runtest test_array "test4" none 1 3
runtest test_array "test5" none 1 3
runtest test_array "test6" none 1 3

printResults
