/**
 * CS180 - Lab 03 - StringManipulator
 *
 * Creates a Unix-Style User name and email address given a name and domain
 *
 * @everettr Ryan Everett, everettr@purdue.edu
 */
import java.util.*;

public class StringManipulator {
    /**
     * @param fullName contains the person's
     * first and last name separated by a space
     * @return user name
     */
    public String makeUserName(String fullName) {
        if (fullName == null) {
            return null;
        } else {
            Character firstChar = fullName.charAt(0);
            String firstInitial = firstChar.toString();
            int spaceCharIndex = fullName.indexOf(" ");
            String lastName = fullName.substring(spaceCharIndex + 1);
            firstInitial = firstInitial.toLowerCase();
            lastName = lastName.toLowerCase();
            return firstInitial + lastName;
        }
    }
    /**
     * @param userName contains the person's
     * first initial+last name. Generated by
     * makeUserName
     * @param domain contains the domain of
     * the desire email address
     * @return email
     */
    public String makeEmail(String userName, String domain) {
        if (userName == null || domain == null) {
            return null;
        } else {
            domain = domain.toLowerCase();
            return userName + "@" + domain;
        }
    }

    public static void main(String[] args) {
        //Output and Instruction strings
        final String INSTRUCTION1 = "Enter the Full Name of the person. First Name followed by Last Name.";
        final String INSTRUCTION2 = "Enter the domain";
        final String OUTPUT1 = "The user name for the person is: ";
        final String OUTPUT2 = "The email id for the person is: ";

        Scanner s = new Scanner(System.in);
        StringManipulator sM = new StringManipulator();
        System.out.println(INSTRUCTION1);
        String fullName = s.nextLine();
        System.out.println(INSTRUCTION2);
        String domain = s.nextLine();
        String userName = sM.makeUserName(fullName);
        String email = sM.makeEmail(userName, domain);
        if (userName == null || email == null) {
            System.out.println("null");
        } else {
            System.out.println(OUTPUT1 + userName);
            System.out.println(OUTPUT2 + email);
        }
    }
}
