#!/bin/bash

(make clean; make) || exit 1

source ../../tester/testall

runtest test_bits "test1" none 1 3
runtest test_bits "test2" none 1 3
runtest test_bits "test3" none 1 3
runtest test_bits "test4" none 1 3
runtest test_bits "test5" none 1 3

printResults
