#!/bin/bash

echo "------ Test 0 -------"

cd ../
make -f Makefile clean

make -f Makefile

cd test/

echo "Check if program exists"

if [ ! -f ../maxmin ]; then
	echo ./maxmin does not exist
	exit 1
fi

echo ">>> Test0 passed"
exit 0
