#!/usr/bin/expect -f

puts "=========== Running Test 3 ============"

source testing.tcl

set timeout 2
spawn ../maxmin
match_max 100000
myexpect  "Finding maximum among three numbers a,b and c\r
Type a and <enter>: "
send -- "120\r"
myexpect  "120\r
Type b and <enter>: "
send -- "23\r"
myexpect  "23\r
Type c and <enter>: "
send -- "34\r"
myexpect  "34\r
Numbers are not in the correct range \[0-100\]\r
Do you want to continue? Type y/n and <enter>"
send -- "y\r"
myexpect  "y\r
Type a and <enter>: "
send -- "23\r"
myexpect  "23\r
Type b and <enter>: "
send -- "56\r"
myexpect  "56\r
Type c and <enter>: "
send -- "145\r"
myexpect  "145\r
Numbers are not in the correct range \[0-100\]\r
Do you want to continue? Type y/n and <enter>"
send -- "y\r"
myexpect  "y\r
Type a and <enter>: "
send -- "123\r"
myexpect  "123\r
Type b and <enter>: "
send -- "345\r"
myexpect  "345\r
Type c and <enter>: "
send -- "32\r"
myexpect  "32\r
Numbers are not in the correct range \[0-100\]\r
Do you want to continue? Type y/n and <enter>"
send -- "n\r"
myexpect eof

puts ">>>>>> Test3 passed"
exit 0
