#!/usr/bin/expect -f

puts "=========== Running Test 1 ============"

source testing.tcl

set timeout 2
spawn ../high-low
match_max 100000
myexpect  "Welcome to the High Low game...\r
Think of a number between 1 and 100 and press <enter>"
send -- "\r"
myexpect  "\r
Is it higher than 50? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 75? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 62? (y/n)\r
"
send -- "n\r"
myexpect  "n\r
Is it higher than 56? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 59? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 60? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
Is it higher than 61? (y/n)\r
"
send -- "y\r"
myexpect  "y\r
\r
>>>>>> The number is 62\r
\r
Do you want to continue playing (y/n)?"
send -- "n\r"
myexpect eof

puts ">>>>>> Test1 passed"
exit 0
