# Makefile for Computer Networks and Internets TCP API
# Solaris Version

DEFS	= -DSOLARIS
INC_DIR	= ../h
INCLUDE = -I$(INC_DIR)
LD	= ld
CC	= gcc
LIBS	= -lsocket -lnsl -lpthread 
FLAGS   = -c -g

CNAIAPI_LIB = cnaiapi.o

API_DIR = ../api
API_SRC = 	appname_to_appnum.c	\
		cname_to_comp.c		\
		await_contact.c		\
		make_contact.c		\
		send_eof.c		\
		cnaiapi_init.c

API_OBJ = $(API_SRC:.c=.o)

APP_DIR = ../apps
APP_SRC = 	server.c		\
		client.c		\
		readln.c

APP_OBJ = $(APP_SRC:.c=.o)
APP_EXE = server client 
CFILES = $(API_DIR)/*.c $(APP_DIR)/*.c

apps: $(APP_EXE)

server: cnaiapi.o server.o readln.o
	$(CC) -o $@ $(LIBS) $(CNAIAPI_LIB) server.o readln.o
client: cnaiapi.o client.o readln.o
	$(CC) -o $@ $(LIBS) $(CNAIAPI_LIB) client.o readln.o

$(APP_OBJ):
	$(CC) -c $(INCLUDE) $(FLAGS) $(DEFS) $(APP_DIR)/$(@:.o=.c)
$(CNAIAPI_LIB): $(API_OBJ)
	$(LD) -r -o $(CNAIAPI_LIB) $(API_OBJ)
$(API_OBJ):
	$(CC) $(INCLUDE) $(FLAGS) $(DEFS) $(API_DIR)/$(@:.o=.c)

clean:
	\rm -rf *.o core $(CNAIAPI_LIB) $(APP_EXE)

# API Dependancies
appname_to_appnum.o: $(API_DIR)/appname_to_appnum.c $(INC_DIR)/cnaiapi.h
await_contact.o: $(API_DIR)/await_contact.c $(INC_DIR)/cnaiapi.h
cname_to_comp.o: $(API_DIR)/cname_to_comp.c $(INC_DIR)/cnaiapi.h
make_contact.o: $(API_DIR)/make_contact.c $(INC_DIR)/cnaiapi.h
send_eof.o: $(API_DIR)/send_eof.c $(INC_DIR)/cnaiapi.h

client.o: $(APP_DIR)/client.c $(INC_DIR)/cnaiapi.h
server.o: $(APP_DIR)/server.c $(INC_DIR)/cnaiapi.h

readln.o: $(APP_DIR)/readln.c $(INC_DIR)/cnaiapi.h
