#!/bin/sh

grade0=0
grade0max=5
./test0 && grade0=`expr $grade0 "+" 5`

grade1=0
grade1max=9
./test1 && grade1=`expr $grade1 "+" 9`

grade2=0
grade2max=9
./test2 && grade2=`expr $grade2 "+" 9`

grade3=0
grade3max=7
./test3 && grade3=`expr $grade3 "+" 7`


total=`expr $grade0 + $grade1 + $grade2 + $grade3`

totalmax=`expr $grade0max + $grade1max + $grade2max + $grade3max`

echo   "-------------------------------------------------"
echo   "User:  $1 "
echo   "-------------------------------------------------"
printf "Test0:          	 %-3d%s%-3d\n" $grade0 " of " $grade0max
printf "Test1:          	 %-3d%s%-3d\n" $grade1 " of " $grade1max
printf "Test2:                   %-3d%s%-3d\n" $grade2 " of " $grade2max
printf "Test3:                   %-3d%s%-3d\n" $grade3 " of " $grade3max
echo   "--------------------------------------------------"
printf "Total:                   %-3d%s%-3d\n" $total " of " $totalmax

#Do not remove or comment these lines. They are used for monitoring progress.
labout=/homes/cs240/LABOUT/lab2/$USER/total.txt
cat total.out >> $labout
git add -A >> .local.git.out
git commit -a -m "$total of $totalmax" >> .local.git.out


