#!/usr/bin/expect -f

puts "=========== Running Test 1 ============"

source testing.tcl

set timeout 2

spawn ../circle
match_max 100000
myexpect  "Finding area and circumference of a circle given a radius\r
Enter the radius and <enter>: "
send -- "23\r"
myexpect  "23\r
Area is = 1661.060000 \r
Circumference is = 144.440000 \r
Do you want to continue? Type y/n and <enter>"
send -- "y\r"
myexpect  "y\r
Enter the radius and <enter>: "
send -- "12\r"
myexpect  "12\r
Area is = 452.160000 \r
Circumference is = 75.360000 \r
Do you want to continue? Type y/n and <enter>"
send -- "n\r"
myexpect eof

puts ">>>>>> Test1 passed"
exit 0
