#!/bin/bash

echo "------ Test 0 -------"

cd ../
make -f Makefile clean

make -f Makefile

cd test/

echo "Check if program exists"

if [ ! -f ../circle ]; then
	echo ./circle does not exist
	exit 1
fi

echo ">>> Test0 passed"
exit 0
