#!/bin/bash

(make clean; make) || exit 1

source ../../tester/testall

runtest sort_array "5 4 1 2 3" none 1 2
runtest sort_array "5 -4 1 2 3" none 1 2
runtest sort_array " -1 -4 -12 -2 -300" none 1 3
runtest sort_array "0 0 0 0 0" none 1 3
runtest sort_array "1 100 1000 -1 -100 -1000" none 1 3
runtest sort_array "6 5 3 2 1 4 6 7 8 9 5 34 1 2 3 34 9 8" none 1 3

printResults
