#!/bin/bash

export LAB=lab5

OLD_PATH=${PATH}
PATH=".:${PATH}"

(make clean; make) || exit 1

total=0
totalmax=0

rm -f total.txt *out total.txt
touch none

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  compout=$4
  grade=$5
  totalmax=`expr $totalmax + $grade`;
  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="$prog $args $inputdescr"

  echo "======= $descr ==========="
  echo > none

  #Run tested program
  if [ $compout -eq 0 ]; then
    eval "./$prog $args < $testinput > $prog.out"
    if [ $? -eq 0 ]; then
          #cat $prog.out
          echo Test passed...;
          printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
          total=`expr $total + $grade`;
    else
          cat $prog.out
          echo "*****Test Failed*****";
          printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
    fi
  else
    eval "./$prog $args < $testinput > $prog.out"
    eval "./$prog.org $args < $testinput > $prog.org.out"
    diff $prog.out $prog.org.out > diff.out
    if [ $? -eq 0 ]; then
          #cat $prog.out
          echo Test passed...;
          printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
          total=`expr $total + $grade`;
    else
          echo "*****Test Failed*****";
          echo ------ Your Output ----------
          cat $prog.out
          echo ------ Expected Output ------
          cat $prog.org.out
          echo ------ Difference -----------
          cat diff.out
          echo -----------------------------
          printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
    fi
  fi
  echo
}

function printResults {
  echo
  echo   "-------------------------------------------------"
  echo   "CS240: $LAB. $USER "
  echo   "-------------------------------------------------"
  cat total.txt
  echo   "-------------------------------------------------"
  echo   "CS240: $LAB. $USER $PWD" `date` " Total: " $total of $totalmax >> total.out
  echo "$total" >> total.out
  echo "$totalmax" >> total.out
  #echo "$total/$totalmax" >> total.out
  cat  total.out
  #echo >> total.out

  #cat total.out
  #head -1 >> total.out
  #cat total.out >> .local.total.out

}

function gitadd
{
  files=$1
  git add $files total.out >> .local.git.out
  git commit -a -m "$total of $totalmax" >> .local.git.out
  export labout=/homes/cs240/LABOUT/$LAB/$USER/total.txt
  cat total.out >> $labout
}


# PATH=${OLD_PATH}
# #Do not remove or comment these lines. They are used for monitoring progress.
# labout=/homes/cs240/LABOUT/$LAB/$USER/total.txt
# cat total.out >> $labout
# git add *.h *.c total.out >> .local.git.out
# git commit -a -m "$total of $totalmax" >> .local.git.out
